force-app/main/halwaKadai/objects/Product2/fields/HomePage_Visible__c.field-meta.xml
<CustomField>
    <fullName>HomePage_Visible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HomePage_Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/halwaKadai/objects/Product2/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/halwaKadai/objects/Product2/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Best Seller</fullName>
            </value>
            <value>
                <fullName>Popular</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Trending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/halwaKadai/objects/Product2/recordTypes/HalwaShop.recordType-meta.xml
<RecordType>
    <fullName>HalwaShop</fullName>
    <active>true</active>
    <label>HalwaShop</label>
</RecordType>

force-app/main/halwaKadai/classes/Halwakadai_HelperClass.cls
/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : Halwa_HelperClass
 * Author          : <YourName>
 * Created Date    : Jan 4, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Jan 4, 2026
 * Description     : This class implements for......
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Jan 4, 2026  │ <YourName>   │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */

public class Halwakadai_HelperClass {

	@AuraEnabled(cacheable=true)
	public static List<Product2>  getProductsDetails() {
		List<Product2> halwaList = [SELECT  Name, ProductCode, Description, StockKeepingUnit, Image_URL__c, HomePage_Visible__c, Tag__c, Price__c,(SELECT Id, UnitPrice FROM PricebookEntries WHERE IsActive = true ORDER BY CreatedDate DESC LIMIT 1) FROM Product2 WHERE RecordType.DeveloperName  = 'HalwaShop'];
		for(Product2 halwa : halwaList){
			system.debug(halwa);
		}
		return halwaList;
	}

    @AuraEnabled
	public static Id createOrder(List<Map<String,Object>> products) {
		Order newOrder = new Order(
			AccountId = '001GA00005KAsGgYAL',
			ContractId = '800GA000000b86cYAA',
			EffectiveDate = Date.today(),
			Status = 'Draft',
			Pricebook2Id = '01sGA00000Zwd4SYAR'
		);
		insert newOrder;

		List<OrderItem> orderItems = new List<OrderItem>();

	for (Map<String,Object> prod : products) {
		if(((Decimal) prod.get('quantity')).intValue()>0){
			Id pricebookId   = (Id) prod.get('pricebookId');
			system.debug(pricebookId);
			Decimal unitPrice = (Decimal) prod.get('price');

			// Safe conversion for quantity
			Integer quantity = 0;
			Object qtyObj = prod.get('quantity');
			if (qtyObj != null) {
				if (qtyObj instanceof Decimal) {
					quantity = ((Decimal) qtyObj).intValue();
				} else if (qtyObj instanceof Double) {
					quantity = ((Double) qtyObj).intValue();
				} else if (qtyObj instanceof Integer) {
					quantity = (Integer) qtyObj;
				}
			}

			if (pricebookId != null && quantity > 0) {
				orderItems.add(new OrderItem(
					OrderId = newOrder.Id,
					PricebookEntryId = pricebookId,
					Quantity = quantity,
					UnitPrice = unitPrice
				));
			}
		}
	}


		if (!orderItems.isEmpty()) {
			insert orderItems;
		}

		return newOrder.Id;
	}



}